name: Deploy Telegram Bot

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install pyTelegramBotAPI

    - name: Validate env vars
      run: |
        if [ -z "$TELEGRAM_TOKEN" ]; then
          echo "ERROR: TELEGRAM_TOKEN is not set!"
          exit 1
        fi
        echo "Environment variables check passed"

    - name: Run bot
      run: |
        python app.py