name: Run Telegram Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # 

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        JSONBIN_API_KEY: ${{ secrets.JSONBIN_API_KEY }}
        JSONBIN_BIN_ID: ${{ secrets.JSONBIN_BIN_ID }}
      run: |
        # Заменяем плейсхолдеры на реальные значения из GitHub Secrets
        sed -i "s/BOT_TOKEN = \".*\"/BOT_TOKEN = \"${BOT_TOKEN}\"/g" hoh.py
        sed -i "s/CHANNEL_ID = \".*\"/CHANNEL_ID = \"${CHANNEL_ID}\"/g" hoh.py
        sed -i "s/JSONBIN_API_KEY = \"YOUR_JSONBIN_API_KEY\"/JSONBIN_API_KEY = \"${JSONBIN_API_KEY}\"/g" hoh.py
        sed -i "s/JSONBIN_BIN_ID = \"YOUR_JSONBIN_BIN_ID\"/JSONBIN_BIN_ID = \"${JSONBIN_BIN_ID}\"/g" bot.py
        python bot.py
